version: "3.4"
services:
  centos7postgresbase:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: aursu/pgbuild:7-base
  centos6postgresbase:
    build:
      context: .
      dockerfile: Dockerfile.6-base
    image: aursu/pgbuild:6-base
  postgresql6build:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el6
    image: aursu/pgbuild:el6
  postgresql7build:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/pgbuild:el7

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
