FROM aursu/rpmbuild:6-build

USER root
RUN yum -y install \
        gettext \
        multilib-rpm-config \
        openssl-devel \
        pam-devel \
        perl-ExtUtils-MakeMaker \
        readline-devel \
        uuid-devel \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
